- README.md
> Add link to `doctornpm`

- .github/workflows/stage-pull-request.yml
- CONTRIBUTING.md
> docs: add note about preferring npm 7

- content/getting-started/troubleshooting/try-the-latest-stable-version-of-npm.mdx
The command prompt needs to be run as an administrator, or else attempting to update results in this error below:
```
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\nodejs\node_modules\.staging
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'
npm ERR!  [OperationalError: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'mkdir',
npm ERR!     path: 'C:\\Program Files\\nodejs\\node_modules\\.staging'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM', …
```
> Add detail to instructions for Windows

- content/packages-and-modules/updating-and-managing-your-published-packages/unpublishing-packages-from-the-registry.mdx
- content/policies/index.mdx
- src/gatsby-theme-doctornpm/nav.yml
- src/nav-base.yml
Updating the Index of Policy. Removed reference to the deleted Policy for `receiving-reports`
> Updated index policy page

- content/getting-started/setting-up-your-npm-user-account/about-two-factor-authentication.mdx
Adds the missing CLI command reference for changing a package's 2FA requirements.
> feat: add package 2FA requirements CLI command

- content/getting-started/setting-up-your-npm-user-account/configuring-two-factor-authentication.mdx
Fixes incorrect image / instructions
> doc: update 2fa docs

- content/getting-started/setting-up-your-npm-user-account/configuring-two-factor-authentication.mdx
> doc: add Microsoft authenticator

- src/nav-base.yml
> doc: update-nav

- .github/workflows/publish.yml
- .github/workflows/update-cli.yml
> tools: update node in actions

- content/packages-and-modules/securing-your-code/verifying-the-pgp-signature-for-a-package-from-the-npm-public-registry.mdx
> feat: update pgp examples to use npm commands

- content/organizations/creating-and-managing-organizations/converting-your-user-account-to-an-organization.mdx
> fix: correction of duplication of the word "your"

- .github/CODEOWNERS
Adds PM to everything and CLI team for CLI doc changes
> tools: add code owners

- content/policies/privacy.mdx
Fixes a broken link I happened to notice.
> Fix broken link

- content/getting-started/setting-up-your-npm-user-account/configuring-two-factor-authentication.mdx
This is already covered in the previous sentence.
> remove duplicated sentence

- content/getting-started/setting-up-your-npm-user-account/about-two-factor-authentication.mdx
- content/getting-started/setting-up-your-npm-user-account/accessing-npm-using-2fa.mdx
- content/getting-started/setting-up-your-npm-user-account/configuring-two-factor-authentication.mdx
update about beta status of security-key using webauth
> update about beta status of security-key using webauth

- content/getting-started/setting-up-your-npm-user-account/about-two-factor-authentication.mdx
> Update 2FA ref to wiki

- package-lock.json
`npm ci` is broken due to out of sync deps. Let's fix this.
> deps: fix package-lock

- package-lock.json
> deps: fix audit warnings

- content/packages-and-modules/updating-and-managing-your-published-packages/adding-collaborators-to-private-packages-owned-by-a-user-account.mdx
Fixes a minor typo, missing the word "add".
> Typo, missing "add"

- content/packages-and-modules/contributing-packages-to-the-registry/specifying-dependencies-and-devdependencies-in-a-package-json-file.mdx
> docs: fix typo with punctuation in example code

- cli/lib/redirects.js
- cli/test/transform.js
- content/cli/v6/configuring-npm/package-locks.md
> fix: redirect /files/packages-locks to v6 page

- theme/src/components/header.js
- theme/src/components/npm-logo.js
Added a title to the homepage link. 
Related to https://github.com/github/accessibility-audits/issues/2739
> Add a title to the homepage link

- src/theme/nav.yml
- theme/src/components/variant-select.js
We can press enter key to open selected version page
> Enter key opens version page

- src/theme/nav.yml
- theme/src/components/variant-select.js
Suggested changes: https://github.com/github/accessibility-audits/issues/2797#issuecomment-1293469881
https://github.com/github/accessibility-audits/issues/2797#issuecomment-1293469881
> update for suggestion

- content/getting-started/setting-up-your-npm-user-account/accessing-npm-using-2fa.mdx
- content/organizations/creating-and-managing-organizations/renaming-an-organization.mdx
- content/organizations/managing-teams/about-developers-team.mdx
- content/policies/logos-and-usage.mdx
I searched the documentation for typos and corrected any that I found :-)
> Fixed several typos

- theme/src/components/layout.js
Demo:
https://user-images.githubusercontent.com/103434939/197803016-bf3196d2-9289-4f09-9138-3057f3e34be2.mov
https://github.com/github/accessibility-audits/issues/2745
> Changed paddings for table of contents

- content/packages-and-modules/contributing-packages-to-the-registry/creating-a-package-json-file.mdx
Issue : https://github.com/github/accessibility-audits/issues/2743
Fix : This PR implements a fix that has been suggested in acceptance criteria : https://github.com/github/accessibility-audits/issues/2743#issue-1320802451
Screenshot :
> Making a link more descriptive

- theme/src/components/mobile-search.js
https://github.com/github/accessibility-audits/issues/2744
> Changed placeholder text

- theme/src/components/layout.js
- theme/src/components/table-of-contents.js
Demo:
https://user-images.githubusercontent.com/103434939/196456079-919f2079-6b8d-472d-bdb9-2269a88b7b42.mov
https://github.com/github/accessibility-audits/issues/2747
> Added aria-labelledby for table of content

- CONTRIBUTING.md
Minor:
- `gatsby` --> `Gatsby` as per https://www.gatsbyjs.com/
- `Mdx` --> `MDX` as per https://mdxjs.com/
- `temas` --> `teams` in example
> CONTRIBUTING.md: minor, capitalization, typo

- CONTRIBUTING.md
Minor:
- `markdown` --> `Markdown` ([source](https://www.google.com/search?q=%22markdown%22))
- Meant to do this in #282
> CONTRIBUTING.md: minor, capitalization

- content/getting-started/configuring-your-local-environment/downloading-and-installing-node-js-and-npm.mdx
> Fix broken links in `downloading-and-installing-node-js-and-npm#overview`

- theme/src/components/nav-items.js
- theme/src/components/sidebar.js
Demo:
https://user-images.githubusercontent.com/103434939/198038739-c46d54f6-ce2c-4c60-8c6d-dc9b8867e7d4.mov
https://github.com/github/accessibility-audits/issues/2799
> Added role for sidebar-nav

- content/packages-and-modules/getting-packages-from-the-registry/using-npm-packages-in-your-projects.mdx
Removed @ from unscoped package name
> Remove @ from unscoped package name

- content/organizations/managing-organization-members/removing-members-from-your-organization.mdx
> Add 'no' to 8th line

- theme/src/components/code.js
- theme/src/components/drawer.js
Eslint issues fixed for all bellow
- jsx-a11y/no-noninteractive-tabindex
- jsx-a11y/click-events-have-key-events
- jsx-a11y/no-static-element-interactions
Issue: [#npm/datadog](https://app.datadoghq.com/dashboard/fq9-kaf-m3a?tpl_var_catalog_service=npm&from_ts=1677584886630&to_ts=1677588486630&live=true)
> Eslint issues fixed:

- content/packages-and-modules/introduction-to-packages-and-modules/about-packages-and-modules.mdx
Fix documentation page so it will show correct formatting.
> Remove <div class="note"> which breaks formatting

- content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
As of 6.6.2, lerna supports provenance via all the specified options for third party tools.
https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598
> chore: lerna supports provenance

- content/organizations/managing-organization-members/organization-roles-and-permissions.mdx
> Update org role permissions

- content/integrations/integrating-npm-with-external-services/about-access-tokens.mdx
- content/integrations/integrating-npm-with-external-services/creating-and-viewing-access-tokens.mdx
- 50 tokens to 1000 tokens
- Remove max 365 days expiry
> Updated GAT restrictions

- content/packages-and-modules/updating-and-managing-your-published-packages/unpublishing-packages-from-the-registry.mdx
The unpublishing requirements link is point to the section which doesn't exist. Replace it with Publish Policy link
> Update Unpublish Requirement Link

- theme/gatsby-config.js
- theme/src/components/code.js
> fix: allow easier selection of code blocks

- content/policies/unpublish.mdx
This clarifies the conditions for unpublishing a package.
Alternatives are listed in the first post of #29.
Fixes #29
> doc: clarify unpublish policy (fix #29)

- theme/src/components/mobile-search.js
- theme/src/components/search.js
Label/title is not defined for "Search npm Docs" edit field.
aria-label is added for the search input field.
Fixes #5930
Fixes url: https://github.com/github/accessibility-audits/issues/5930
Screen Record for the fix:
[https://github-grid.enterprise.slack.com/files/U05R2JD2H8S/F061LH9FCJU/screenshare_-_2023-10-12_2_28_31_pm.webm](url)
> added an aria-label for the search input field

- theme/src/components/heading.js
- theme/src/components/hero-layout.js
- theme/src/components/layout.js
- theme/src/components/wrap-root-element.js
- theme/src/use-slugger.js
> fix: scope slug generation to each page

- content/packages-and-modules/securing-your-code/about-audit-reports.mdx
> docs: remove duplicate title in 'about-audit-reports.mdx'

- .github/actions/create-check/action.yml
- .github/workflows/audit.yml
- .github/workflows/ci-cli.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/post-dependabot.yml
- .github/workflows/publish.yml
- .github/workflows/update-cli.yml
- cli/package.json
- package-lock.json
- package.json
- chore: bump @npmcli/template-oss to 4.22.0
- chore: postinstall for dependabot template-oss PR
> chore: bump @npmcli/template-oss to 4.22.0

- content/organizations/creating-and-managing-organizations/requiring-two-factor-authentication-in-your-organization.mdx
This PR turns the two dots into one:
> fix: correction of duplication of "."

- webpack.config.js
Add a cautionary comment about `devServer` being a security problem.
https://github.com/advisories/GHSA-wr3j-pwj9-hqq6
> chore: Update webpack.config.js

- content/packages-and-modules/introduction-to-packages-and-modules/package-scope-access-level-and-visibility.mdx
The section heading seems inappropriate, I've updated it to relate to the section.
> fix: appropriate heading

- content/getting-started/setting-up-your-npm-user-account/configuring-two-factor-authentication.mdx
English is not my native language but I do not know what are *"biometric devices such as Apple Touch ID, Face ID, or Windows Hello"*. I propose to define that biometric devices (hardware) **feature** the remaining items (technologies/softwares).
Please forgive me if I misunderstood the meaning.
> docs: clarify definition of biometric devices

- content/packages-and-modules/contributing-packages-to-the-registry/creating-a-package-json-file.mdx
Induce minor readability changes:
- Provide example for website in "author" parameter
- Add description in package.json code example as advised in the documentation
- Highlight & edit npm init command
> docs: Update creating-a-package-json-file.mdx 

- content/packages-and-modules/contributing-packages-to-the-registry/package-name-guidelines.mdx
- Capitalization
- Add ` Does not contain uppercase letters`
- Remove redundant bulletpoint
- Spelling checks
Closes #136
> Docs: Package name guidlines  (Uppercase exclusion)

- content/cli/v11/configuring-npm/package-json.mdx
Fixed grammatical error:  `that` -> `than`
> docs: fix typo

- .github/dependabot.yml
- package.json
We are grown up and could use a little more independence
> chore: weekly dependabot updates

- package-lock.json
- package.json
Bump the `eslint-config-prettier` package version `10.0.2` to `10.1.8`
> Bump the `eslint-config-prettier` package
