content/cli/v6/using-npm/scripts.md, content/cli/v7/using-npm/scripts.md, content/cli/v7/using-npm/workspaces.md
* nodejs -> Node.js
* javascript -> JavaScript
=> Fix some name stylings

content/policies/unpublish.mdx
The current link to the blog post results in a 404 due to an extra `-` in the URL.
Refs: https://github.com/npm/policies/pull/154
=> Fix broken link to unpublish policy blog post

.github/workflows/update-cli.yml
Remove the cli directory before doing the import; this ensures that if
some file `foo.md` is deleted that the deletion propagates.
/cc @MylesBorins
=> cli: clean up cli docs before importing them

content/policies/disputes.mdx
Currently it specifies `module` for the naming dispute.
=> policies: the dispute policy is for all naming disputes

content/packages-and-modules/getting-packages-from-the-registry/downloading-and-installing-packages-locally.mdx
One word typo fix from `instalsx` to `installs`
=> fix: typo from 'instalsx' to 'installs'

content/about-npm/index.mdx
It isn't kept up to date anymore
=> chore: remove npm-weekly reference

content/integrations/integrating-npm-with-external-services/using-private-packages-in-a-ci-cd-workflow.mdx
There was an invalid link on 'automation token' which leads to 404, also not unified style of link presentation because other links have quotes. 
Use the mdx anchor tag [create-token] to link to proper document.
Prettify mdx file.
=> docs: fix invalid link and unify link presentation

content/organizations/managing-teams/managing-team-access-to-organization-packages.mdx, src/shared.js
While reading the documentation I found adjacent"the" words in sentences. This PR addresses all sentences with two adjacent "the" words.
=> fix: typos

content/integrations/integrating-npm-with-external-services/using-private-packages-in-a-ci-cd-workflow.mdx
I think that this paragraph meant to reference storing secrets in a "password manager," not a "package manager." The latter doesn't really make sense.
=> Fix password manager typo

.github/workflows/publish.yml, .github/workflows/stage-pull-request.yml, .github/workflows/update-cli.yml
there were only minor differences between the publish and update-cli workflows so the most direct route to removing the need for the deploy key here was to add the second push to the `dist` branch
update:
i also added a commit that rotates the secret in use for the docs-staging deploy and another updating the bot account information in all of the workflows
=> chore: tweak update-cli workflow a bit to remove the deploy key

content/integrations/integrating-npm-with-external-services/revoking-access-tokens.mdx
This was the only place it was documented. We've updated this behavior
as we no longer have the same risk to tokens on password reset with
login verification
=> doc: password reset no longer revokes tokens

content/packages-and-modules/contributing-packages-to-the-registry/creating-and-publishing-scoped-public-packages.mdx
I made it, so the italic characters get escaped. Otherwise, "replacing" would be written in italic.
=> escaping italic formatting

content/packages-and-modules/contributing-packages-to-the-registry/creating-a-package-json-file.mdx
The previous commands seem to result in errors like this:
```
npm WARN config init.author.name Use `--init-author-name` instead.
```
Even more confusingly, if you run the old commands then you end up with the dot-based syntax in your config, which surfaces as an error even if you use the *correct* syntax for new entries going forward:
```
> npm set init.author.email "example-user@example.com"
npm WARN config init.author.email Use `--init-author-email` instead.
> npm set init-author-email "example-user@example.com" # note: correct syntax!
npm WARN config init.author.email Use `--init-author-email` instead.
```
It might be helpful to explain that in these docs, although I haven't tried to tackle it in this PR.
=> Update config option formatting for the init command.

.github/workflows/publish.yml
There is now support for deploying pages by actions bypassing the need to
upload to a branch, this significantly simplifies the overall process
and removed the need for a "dist" branch.
I'm about 99% confident this will work out of the box, I've tested on
two personal websites already.
=> tools: do pages deployment via actions

CONTRIBUTING.md, README.md
This updates the docs to show how the staging deployments for this site now work. See [this comparison](https://github.com/npm/documentation/compare/a760337bff12d0707ff78dae4fab94720c6b558a...155df31fd677735a67cd96dc3138d7a34b761932) for the changes to CI.
Notable changes:
- `pull_request_target` is included in the main `publish.yml` workflow. That event controls which ref is checked out and whether the deploy job is a preview or not.
- For all other events, `main` is explicitly checked out. This allows us to push commits when fetching/updating the CLI docs, and then the call the `publish.yml` as a reusable workflow but still have it deploy the latest.
- `stage-pull-request.yml` has been removed and all deployments (production and preview) occur in this repo
These changes are already in …
=> docs: update staging deployment flow

.github/workflows/publish.yml
Adding this permission is necessary to support private repos
=> tools: pages read permission to build-and-upload

.github/workflows/update-cli.yml
The release process for the CLI now handles manually triggering a
`workflow_dispatch` on the update-cli workflow.
This will also prevent any prerelease versions getting published to the
the documentation site since it build directly from `latest` where
prerelease development will be happening.
A future PR will change that behavior so docs are built from registry
tags.
=> fix: remove update cli cronjob

.github/workflows/publish.yml
The GitHub Pages team recently [upstreamed](https://github.com/actions/deploy-pages/pull/61) our `paper-spa/deploy-pages` support for Pages preview sites to the official `actions/deploy-pages` Action.
Although it is still **only available as a limited alpha**, we didn't want to incur too much feature drift between the two repositories. Additionally, this alpha feature has already been mentioned in public forums prior to now, so it's no secret.
You may now utilize the preview deployments feature using any of the following `uses` configurations in your Actions workflow (from most specific/secure to least):
```
uses: actions/deploy-pages@c2379ec5e719a934ec613038d081879b58c9d7df
uses: actions/deploy-pages@v1.1.0
uses: actions/deploy-pages@v1
uses: actions/deploy-pages@main
```
Feel free to …
=> Use official `actions/deploy-pages` Action

content/packages-and-modules/getting-packages-from-the-registry/resolving-eacces-permissions-errors-when-installing-packages-globally.mdx
It appears that step 1 was added later but the reference was not updated. This makes it match again.
=> docs: Fix reference to step numbers.

theme/src/components/header.js, theme/src/components/hero-layout.js, theme/src/components/layout.js, theme/src/components/page-footer.js, theme/src/components/sidebar.js
There are no landmarks defined for 'npm Docs' page.
`role` attributes added to required blocks
Note: Maybe there are other places to set landmarks, if exist, let me know
Related to [accessibility-audits/issues/2738](https://github.com/github/accessibility-audits/issues/2738)
=> ARIA role attributes added

content/packages-and-modules/updating-and-managing-your-published-packages/unpublishing-packages-from-the-registry.mdx
[As per @wraithgar](https://github.com/npm/cli/pull/5742#issuecomment-1290620118)
```diff
- https://docs.npmjs.com/cli/v7/commands/npm-unpublish
+ https://docs.npmjs.com/cli/commands/npm-unpublish
```
=> Remove /v7/ from link (evergreen🌲)

src/theme/nav.yml, theme/src/components/variant-select.js
Upon pressing tab key, the focus moves to the list items available under 'version' dropdown.
https://user-images.githubusercontent.com/91082111/195274849-effa07ea-10d8-492b-b18f-29c843766da4.mov
Fixes: https://github.com/github/accessibility-audits/issues/2797
=> tab index implemented for each variant item

content/about-npm/index.mdx, content/packages-and-modules/getting-packages-from-the-registry/resolving-eacces-permissions-errors-when-installing-packages-globally.mdx, content/policies/privacy.mdx
Continuation of https://github.com/npm/cli/pull/5742
Old link goes to:
https://www.npmjs.com/package/npx
... which is a bit cryptic. Following the link to GitHub goes to:
https://github.com/npm/npx
... which shows:
>This repository has been archived by the owner. It is now read-only.
... up top. Scrolling down reveals:
>⚠️ DEPRECATED: This project has been deprecated - npx is now part of the [npm cli](https://github.com/npm/cli)
... that leads to:
https://github.com/npm/cli
The sidebar gives the link to:
https://docs.npmjs.com/cli/
... and then you just have to search for "npx" (or drill down into "CLI Commands"), and then finally, you get to:
https://docs.npmjs.com/cli/v8/commands/npx
=> Better npx link

theme/src/components/variant-select.js
https://github.com/github/accessibility-audits/issues/2748#issue-1324085140
=> updates for the suggestion

theme/src/components/clipboard-copy.js
Luminosity ratio of focus indicator for ‘Copy to clipboard’ button should be more than 3:1 for the keyboard focus indicator to pass the required ratio.
Issue: https://github.com/github/accessibility-audits/issues/2792
=> color ratio fixed

theme/src/aria-live.js, theme/src/components/clipboard-copy.js
Screen reader did not announce any information upon activating 'Copy to Clipboard' button, with this change it will.
Made as per this [great guiedline](https://github.com/github/thehub/blob/main/docs/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/screenreaders/live-regions-and-screen-reader-announcements.md).
Related to https://github.com/github/accessibility-audits/issues/2795
=> A11y: announce copy to clipboard action

theme/src/components/variant-select.js
Fixed `area-labelledby` on menu and removed aria labels from all version select dropdown items 
Comment: https://github.com/github/accessibility-audits/issues/2748#issuecomment-1316875893
Comment: https://github.com/github/accessibility-audits/issues/2796#issuecomment-1316884749
=> Fix for suggestions

content/packages-and-modules/contributing-packages-to-the-registry/specifying-dependencies-and-devdependencies-in-a-package-json-file.mdx
`creating-a-packge-json-file` to `creating-a-package-json-file`
I'm not sure there is any further explanation needed.
=> Fixes typo in link

content/packages-and-modules/securing-your-code/requiring-2fa-for-package-publishing-and-settings-modification.mdx
The link to [Creating and viewing access tokens](https://docs.npmjs.com/creating-and-viewing-access-tokens) was not correctly defined and is not rendering correctly on [the live site](https://docs.npmjs.com/requiring-2fa-for-package-publishing-and-settings-modification):
=> docs: fix broken link

content/integrations/integrating-npm-with-external-services/creating-and-viewing-access-tokens.mdx
The broken links appear to target sections of the same page but were not specified correctly in the markdown syntax, so they render incorrectly on the [live site](https://docs.npmjs.com/creating-and-viewing-access-tokens):
=> docs: fix broken links on access tokens page

content/packages-and-modules/updating-and-managing-your-published-packages/adding-collaborators-to-private-packages-owned-by-a-user-account.mdx
This:
> ...the invitation **gain** access...
Should be:
> ...the invitation **to** gain access...
=> docs: fix typo on "adding collaborators" page

content/packages-and-modules/contributing-packages-to-the-registry/package-name-guidelines.mdx
On the [package name guidelines page](https://docs.npmjs.com/package-name-guidelines) the current link to the trademark policy https://www.npmjs.com/policies/trademark#the-npm-trademark-policy is dead (I get 404 response page). I have updated it to point to the trademark section of the disputes page here https://docs.npmjs.com/policies/disputes#trademarks (hopefully this is acceptable).
PS: apologies for the many doc fix PRs - I am fixing issues as I encounter them while reviewing the entire docs.npmjs.com site. I am almost done, so there won't be too many more PRs :pray:
=> docs: update link to trademark policy

content/packages-and-modules/contributing-packages-to-the-registry/creating-and-publishing-private-packages.mdx
Link to https://en.wikipedia.org/wiki/Personally_identifiable_information was not provided so [the text](https://docs.npmjs.com/creating-and-publishing-private-packages#reviewing-package-contents-for-sensitive-or-unnecessary-information) was not rendering as a link:
=> docs: fix dangling/broken link

content/threats-and-mitigations/index.mdx
This:
> If you believe you have identified **a** dependency confusion **packages**...
Should read:
> If you believe you have identified a dependency confusion **package**...
=> docs: fix typo on "Threats and Mitigations" page

content/getting-started/setting-up-your-npm-user-account/creating-a-strong-password.mdx
based on the [recent security incident](https://blog.lastpass.com/2022/12/notice-of-recent-security-incident/) I don't think we should still be recommending lastpass
=> doc: remove reference to lastpass

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
Fix a typo in provenance GitHub Actions workflow snippet. The key must be exactly "permissions" (not "permission"). The full example workflow below this snippet uses the correct key.
The final line change was inserted automatically by the GitHub editor (:sweat:), let me know if I should remove it.
Relates to 90fadd9fac8b8b1ee78d7a8b68f0461d64a76d47
=> Fix typo in provenance GitHub Actions workflow snippet

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
Update provenance docs to clarify you need to use a public source repository and add a note for the first version.
=> Update provenance docs

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
This adds an example got publishing with provenance from GitLab CI.
Also code blocks in that document were tagged with their language to provide syntax highlighting. Also the inconsistent indentation was fixed for the GitHub workflow example.
Related to https://github.com/npm/feedback/discussions/968
=> Add example for publishing with GitLab provenance

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
https://github.com/npm/cli/pull/6375 and https://github.com/npm/documentation/pull/684 highlight that GitHub Actions is no longer the only supported provider. we currently link from our semantic-release docs for configuring GitHub Actions, and I would like to do similar for GitLab CI
=> Add GitLab CI to the list of supported CI providers for provenance

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
`publich` should instead read `public` in the GitLab provenance example.
=> Fix typo in generating-provenance-statements.mdx

content/packages-and-modules/introduction-to-packages-and-modules/about-packages-and-modules.mdx
This proposed PR updates a reference to the default branch name from `master` to `main`.
Reference: https://github.com/github/renaming
=> Update default branch name from master to main

theme/src/components/code.js
Ref: https://github.com/github/accessibility-audits/issues/5931
Scrollable content (HTML \<pre\> elements) are not getting focussed while using keyboard tab key to navigate the pages.
Fix is to add the tabIndex property with value 0 for all those elements.
=> Bugfix 5931 scrollable content accessibility

theme/src/components/variant-select.js
1. `label` tag is replaced with `p` tag for removing `htmlFor`
2. `aria-label` is replaced with `aria-labelledby` for reading screen reader
3. removed unwanted `aria-labelledby`
4. commented unwanted `const`
expected result: Screen reader is now announcing the associated label.
References
Fixes #6054
Fixes url: https://github.com/github/accessibility-audits/issues/6054
Screen record is attached
https://github.com/npm/documentation/assets/141764922/ff12e2fe-9908-4084-a350-aeaf69fca86a
=> Bugfix 6054 aria labelledby select version

theme/src/components/variant-select.js
1. added `aria-describedby` for the button
2. reverted the change `aria-labelledby` for the item 
expected result: Screen reader is now announcing the associated label.
Screen shot attached
References
Fixes #6054
Fixes url: https://github.com/github/accessibility-audits/issues/6054
=> aria-describedby is using instead labelledby

theme/src/wrap/root-element.js
Ref:  https://github.com/github/accessibility-audits/issues/5934
Adding a global style so that anchor elements inside text get underline by default.
=> Bugfix for Issue#5934

content/packages-and-modules/getting-packages-from-the-registry/searching-for-and-choosing-packages-to-download.mdx, content/packages-and-modules/updating-and-managing-your-published-packages/deprecating-and-undeprecating-packages-or-package-versions.mdx
Changes Screenshot path from a relative (broken) URL to an absolute URL, inline with all the other screenshot paths. Fixes PROD bug visible at https://docs.npmjs.com/searching-for-and-choosing-packages-to-download
Closes #789
=> Fix broken images

src/components/table-of-contents.js
After #767, the table of contents used the `useDetails()` hook from `@primer/react`.
I believe #775 was reviewed to close https://github.com/github/accessibility-audits/issues/5936 and https://github.com/github/accessibility-audits/issues/5940. This PR implements a similar fix to #775 where the table of contents will always be open by default on small screens. One difference is that since it uses the `useDetails()` hook, if the user closes the table of contents, it will remain closed for the rest of the session.
Closes #776
Closes #775
=> Default table of contents to open on mobile

gatsby-browser.js, src/components/skip-nav.js, src/constants.js, src/page.js
UPD: due to accessibility-related reasons, the `autofocus` attribute idea was parked. Instead, this PR adds the "Skip to search" anchor.
Original:
This PR is a suggestion to add the `autofocus` attribute to the search input. The main driver is that when opening the [docs.npmjs.com](https://docs.npmjs.com/) page, a user needs to set the focus in the input manually to start searching.
There are, however, some [accessibility trade-offs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_considerations) to consider. Therefore, I am open to any feedback and outcome.
=> feat: adding a skip to search anchor

content/policies/privacy.mdx
Changes a few links on the policies page to point to the proper headers.
Removes links from headers, since they were pointing at non-existing anchors and were causing differing header styles on this single page.
- closes https://github.com/github/npm/issues/11173
=> fix: ensure links point to correct anchors

content/packages-and-modules/updating-and-managing-your-published-packages/adding-collaborators-to-private-packages-owned-by-a-user-account.mdx
The current doc on adding collaborator is outdated there's no **+** sign anymore on the package page.
=> fix: update adding a collaborator

CONTRIBUTING.md
Copied from the current version in template-oss, and adapted to fit the docs site instead of a published module.
=> docs: Add conventional commit note to contributing.md

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
Updates the documentation for provenance attestations to include information about verifying attestations. Includes a note about using the latest npm version to ensure that users have the latest verification logic.
=> feat: add info about verifying provenance attestations

content/packages-and-modules/securing-your-code/about-registry-signatures.mdx
=> fix(typo): change keydid to keyid

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
When reading the [npm build provenance doc](https://docs.npmjs.com/generating-provenance-statements), I noticed that the GitLab example was under the GitHub Actions section. This PR just moves the GitLab example to the GitLab section of the doc instead.
I didn't open an issue since it's a tiny, cosmetic change.
=> Move GitLab example for npm build provenance

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
Clarify that the repository url is matched case-sensitive so users don't need to find out by trial and error.
GitHub user names are case-insensitive which means you can use `/username/repository` or `/UserName/repository` as valid repository url. But provenance seems to check for exact match which can be confusing to people adding provenance to their package on GitHub when the url does not satisfy provenance.
=> fix: clarify provenance repository match url is case-sensitive

content/packages-and-modules/updating-and-managing-your-published-packages/deprecating-and-undeprecating-packages-or-package-versions.mdx
Hi npm team, first of all, thanks for your continued effort on npm and documentation!
Add a command example of undeprecating an entire package, which appears to be missing from the documentation currently.
The closest thing currently is this heading + sentence:
> # Undeprecating a package or version
>
> To undeprecate a package, replace "<message>" with "" (an empty string) in one of the above commands.
But I would argue it's a bit open to interpretation, and doesn't explicitly show the command to undeprecate an entire package.
--
=> Add example of undeprecating entire package

content/packages-and-modules/contributing-packages-to-the-registry/creating-node-js-modules.mdx
As I was following the steps in this page - https://docs.npmjs.com/creating-node-js-modules, I noticed the following error when using the published package in the  test-directory:
`Error: Cannot find module 'D:\Learning\npm-docs\use-hello\node_modules\@andrewnessindev\hello\index.js'. Please verify that the package.json has a valid "main" entry`
It turned out that I missed providing the main entry even though this [page already mentions to provide it](https://github.com/npm/documentation/blob/2e10e4ed46f0f58adf4c165e8ef21599bc3b325f/content/packages-and-modules/contributing-packages-to-the-registry/creating-node-js-modules.mdx?plain=1#L20). However, it might be more helpful if the docs clarify which file is referred to when[ it says, "In the …
=> fix: clarify the file name to be used

CONTRIBUTING.md
The syntax for setting env variables is different for powershell and command prompt, so I have mentioned only the command prompt syntax to keep it simple. I think it's sufficient if Windows users just know the syntax needs to be updated.
We could add the windows syntax for setting `GATSBY_CONTENT_ALLOW` and `GATSBY_CONTENT_IGNORE` too, but it feels like an overkill.
Tested by changing the syntax in `package.json` file:
Closes #1172
=> docs: how to run on windows locally

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
This PR updates the "Generating provenance statements" page, updating the GitHub action and introducing minor fixes to the page.
> [!NOTE]
> I have removed the` - run: npm install -g npm` line from the GitHub action since `actions/setup-node` will perform the same.
N/A
=> docs: update generating-provenance-statements page

src/components/table-of-contents.js
The `table-of-content` component shows a scrollbar on Windows even if the content fits:
This fix enables `auto` mode to display scroll bar only if the content is overflowing:
=> fix(toc): display scroll bar only if the content is overflowing

.github/workflows/ci.yml, .github/workflows/publish.yml, scripts/template-oss/ci-yml.hbs, scripts/template-oss/publish-yml.hbs
The only difference that looks like it requires a change is in the new permissions needed for upload-pages-artifact
=> chore: update versions in publish action

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
On the [Generating provenance statements](https://docs.npmjs.com/generating-provenance-statements) page, it has a sample GitHub Actions workflow that has this config:
```yaml
on:
release:
types: [created]
```
However, on GitHub's [Publishing Node.js packages](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) page, the example workflow has
```yaml
on:
release:
types: [published]
```
So it uses `published` instead of `created`.
Tracking down the difference was somewhat difficult... On the [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release) page under "release", it does not document the …
=> Update generating-provenance-statements.mdx --- use the `published` event in the GH Action workflow

content/packages-and-modules/getting-packages-from-the-registry/resolving-eacces-permissions-errors-when-installing-packages-globally.mdx
added a sub folder "lib"
On following the steps mentioned in https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally, 
OS : macOS
After completing step 5, i tried doing `npx lighthouse https://google.com` and it failed with following error 
(Note: website url is just for an example)
(Note: i ran the above command, instead of step 6)
To fix this, make the following change to step 2.
Add a subfolder "lib"
I can create an issue if needed
=> docs: update npm-global folder location

src/theme.js
- https://github.com/github/accessibility-audits/issues/9165
This pull request includes change to the `src/theme.js` file to fix an accessibility issue related to color contrast ratio between `npm link` text #cb0000 and `surrounding text` #1f2328
If the link has no distinct style (such as underline) and luminosity contrast of the link has insufficient contrast ratio with the surrounding text. As a result, users with low vision who experience low contrast cannot detect visually that the text is intended to function as a link.
- [`src/theme.js`](https://github.com/npm/documentation/pull/1270/files#diff-09ce39aad75bba2010ea6e7fb785187ec76b341be11d5f7f2cc6b83839a1b728): Changed the `npm theme` color from `#cb0000` to `#cb3837 ` to meet the minimum contrast 3:1
=> Fix accessibility issue #9165 on color contrast ratio

src/components/page-footer.js, src/mdx/code.js
This pull request includes changes to enhance the user interface and improve code readability in the `src/components/page-footer.js` and `src/mdx/code.js` files. The most important changes involve modifying the display of the latest commit information and enhancing the styling of code comments.
User Interface Enhancements:
* [`src/components/page-footer.js`](diffhunk://#diff-698aaa879c704b0a0f6ffd35d2ef80ef133c897a318c5cdfd1c56e6d85135aefL47-R47): Removed the `color: 'fg.muted'` style from the `Text` component that displays the latest commit information.
Code Readability Improvements:
* [`src/mdx/code.js`](diffhunk://#diff-f3f4e897983cba6337e020c78ef03c356c88f8868bcd19c465eb3c07e8b96625L117-R126): Enhanced the `MonoText` component to apply a specific color (`#747459`) to comments within …
=> [Accessibility fixes]

src/mdx/code.js
This pull request includes a small change to the `src/mdx/code.js` file. The change corrects the color code used for comments in the `Code` component.
* [`src/mdx/code.js`](diffhunk://#diff-f3f4e897983cba6337e020c78ef03c356c88f8868bcd19c465eb3c07e8b96625L123-R123): Adjusted the color code for comments from `#747459` to `#747458` in the `Code` component.
=> [Accessibility bug] set colour contrast ratio 4.5.1

content/packages-and-modules/introduction-to-packages-and-modules/about-packages-and-modules.mdx
Currently we don't document that packages installed through git will not install git submodules in that repo or npm workspaces.
Should clarify:
https://github.com/npm/cli/issues/7554
https://github.com/npm/cli/issues/2774
=> Update docs to include note about submodules & workspaces

src/mdx/code.js
This pull request includes changes to improve the syntax highlighting in the `src/mdx/code.js` file by introducing a color mapping for different token types and simplifying the code structure.
Improvements to syntax highlighting:
* [`src/mdx/code.js`](diffhunk://#diff-f3f4e897983cba6337e020c78ef03c356c88f8868bcd19c465eb3c07e8b96625R46-R50): Added a `colorMap` object to define custom colors for specific token types such as comments, parameter variables, and functions.
Code simplification:
* [`src/mdx/code.js`](diffhunk://#diff-f3f4e897983cba6337e020c78ef03c356c88f8868bcd19c465eb3c07e8b96625L116-R128): Refactored the `Code` component to use the `colorMap` for setting token colors, simplifying the logic for applying styles to tokens.
=> [Fix Accessibility Bug] Refactor code.js to improve syntax highlighting colors

src/mdx/code.js
This pull request includes a small change to the `src/mdx/code.js` file. The change adds a new color mapping for the 'token assign-left variable' to the `colorMap` object.
* [`src/mdx/code.js`](diffhunk://#diff-f3f4e897983cba6337e020c78ef03c356c88f8868bcd19c465eb3c07e8b96625R50): Added color mapping for 'token assign-left variable' in the `colorMap` object.
Missed in the [Previous PR](https://github.com/npm/documentation/pull/1305)
=> [FIX Accessibility] Refactor code.js to add new color mapping for 'token assign-left variable'

content/packages-and-modules/contributing-packages-to-the-registry/creating-a-package-json-file.mdx
- Add missing information as per Issue #1295 
- use secure hyperText Transfer Protocol : https
=> docs: clarify package name rules

src/components/search.js
- Screen reader does not announce the search result information as `No results` on providing invalid input
- [`src/components/search.js`](https://github.com/npm/documentation/pull/1319/files#diff-995f95946b0cbf613b5cf5d8d6335cb1612dcb31907922cd5da28be90a6ff442)
> Add `aria-live` as `polite` to Box element
> Add `announce` function to trigger screen reader announcing the `No results` message when there is no search result
- The screen reader announces the search result information as `No results` on providing invalid input
- https://github.com/github/accessibility-audits/issues/9196
=> Accessibility#9196

src/mdx/components.js
Enabling responsive design on smaller screens by adding the `word-break` CSS property.
Fixes #802
=> core: Fix responsivity issue #802 

src/components/search.js
This issue (https://github.com/npm/documentation/issues/1333) from a couple weeks ago explains the problem pretty thoroughly so if you want more info just look there.
The short version though is that [when `hooks` were deprecated a few months ago](https://github.blog/changelog/2024-07-16-sunset-notice-npm-hooks-api-endpoints/) it surfaced an issue where if a query has a result that  has no `hierarchy` matches the entire page will crash when the dropdown element for the result tries to generate breadcrumbs.
> demo from #1333 
Fixes #1333
I do want to mention that now that you can search for "hooks" without the page crashing, you can now get to the Hooks page for `v10` and the variant dropdown on there behaves a little weird since it can't map a the pages path to a version variant.
=> fix(search): Don't crash the page if a starts a search with the letter "H" 

src/page.js
This pull request removes the `role="main"` attribute from the `PageElement` component in the `src/page.js` file to ensure there is only one main landmark on the 'NPM Docs' page.
- https://github.com/github/accessibility-audits/issues/9212
=> Remove role="main" to ensure 'NPM Docs' page contains only one main landmark

src/components/site-title.js, src/layout.js
This pull request includes a few changes to the `src/components/site-title.js` and `src/layout.js` files to improve the layout and structure of the components.
Layout improvements:
* [`src/layout.js`](diffhunk://#diff-a6d4de2cc6c8127b7cbdf668554367b396b50bea26c46bb805d3bc4d43108994L42-L50): Reordered the `TableOfContents.Desktop` component to be placed after the `Container` component and removed the `flexDirection: 'row-reverse'` style. [[1]](diffhunk://#diff-a6d4de2cc6c8127b7cbdf668554367b396b50bea26c46bb805d3bc4d43108994L42-L50) [[2]](diffhunk://#diff-a6d4de2cc6c8127b7cbdf668554367b396b50bea26c46bb805d3bc4d43108994R61)
Code cleanup:
* [`src/components/site-title.js`](diffhunk://#diff-c25bc0f69ad33508e676865af1c416298095475f259f0a06c386d0b5d9e4b294L7-R7): Removed the redundant …
=> [Fix accessibility] severity 4 Issues

content/nav.yml
v11 docs are up and this field was still left removing v10 in the dropdown
=> fix: v10 in dropdown

cli/lib/build.js, cli/lib/cache.js
currently when new majors are introduced we need to shift around branches / older versions need to be rebuild, so we invalidate the cache here when a new major is introduced
=> fix: drop cache for new majors

content/cli/v10/using-npm/registry.mdx, content/cli/v11/using-npm/registry.mdx, content/cli/v6/using-npm/registry.mdx, content/cli/v7/using-npm/registry.mdx, content/cli/v8/using-npm/registry.mdx, content/cli/v9/using-npm/registry.mdx
With the public communication of the replication feed changes, this PR updates all documentation to remove references to `skimdb.npmjs.com`. All requests will be redirected to `replicate.npmjs.com`.
- Closes https://github.com/github/npm/issues/13321
- https://github.com/orgs/community/discussions/152515
- https://github.blog/changelog/2025-02-26-changes-and-deprecation-notice-for-npm-replication-apis/
=> removing references to skimdb.npmjs.com

content/organizations/managing-teams/managing-team-access-to-organization-packages.mdx
https://github.com/github/npm/issues/13406
=> Swap "team admin" for "package maintainer"

src/components/page-footer.js, src/mdx/components.js
https://github.com/npm/documentation/pull/1367
=> fix: enforce responsive web design via CSS word-break and flex-wrap properties

content/packages-and-modules/securing-your-code/generating-provenance-statements.mdx
As of today, Yarn released [v4.9.0](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.9.0), which adds support for publishing to NPM with provenance statements.
Therefore, I have updated the note about Yarn to include such. I do, however, apologise if there are better ways to word the sentence.
=> docs: update note to mention yarn v4.9.0 supporting provenance

package-lock.json
Reverts npm/documentation#1576
I typed "install", but it's not visible
=> Revert "deps: bump the dependency-updates group across 1 directory with 4 updates"

content/policies/logos-and-usage.mdx
This redirect restores an old link from trademark policies to our logos and usages page.
The logos and usage policies page pretty much have contents from the trademark page that moved back in 2022/2023.
As the previous link is still around, this redirect should function better than a 404.
Supersedes #1587
=> Redirect policies/trademark to logos and usage page

.github/CODEOWNERS
This pull request updates the `.github/CODEOWNERS` file to reassign ownership of several directories and files from individual contributors to the `@npm/cli-team`.
=> chore: Update Codeowners

src/components/header.js, src/components/search.js, src/constants.js
This PR fixes issue #1660  a mobile view bug where the search overlay was overlapping the “npm docs” logo, causing a cluttered visual appearance and also the search button will remain visible even when we click the search Button.
https://github.com/user-attachments/assets/6d9c1ce8-2e7d-400c-8bd2-938907987fa5
https://github.com/user-attachments/assets/e17230f7-11d7-4d24-b101-669afd0e2538
Closes #1660
=> fix(docs): prevent search overlay overlapping branding on mobile  Closes #1660                             

src/components/variant-select.js
This PR addresses [npm/cli#8414](https://github.com/npm/cli/issues/8414), which reports that switching versions using the CLI version dropdown does not properly update the displayed documentation.
- **Refactored `VariantItem` component**:
These changes ensure that when users switch CLI versions from the dropdown, the documentation updates correctly to display the appropriate content for each version.
---
https://github.com/user-attachments/assets/8668e308-ac8d-4f09-b6f4-0ddafa67d317
Closes npm/cli#8414
=> fix(docs): update VariantItem link implementation and separate CLI version docs  Closes npm/cli#8414

content/cli/v11/configuring-npm/package-json.mdx
This PR adds comprehensive documentation for the type field in package.json
Closes #1204
=> docs: add docs for package.json/type

content/organizations/creating-and-managing-organizations/requiring-two-factor-authentication-in-your-organization.mdx
Some small typos found while reading the documentation.
=> docs: fix minor typos in 2FA docs

content/packages-and-modules/securing-your-code/trusted-publishers.mdx
I haven't been quite able to make trusted publishing work in GitLab (see https://github.com/npm/cli/issues/8558), but I do think the example is incorrect. `id_tokens` is not a valid global keyword. It needs to be specified under `default` or a job. I think a job makes more sense.
Reference:
* https://docs.gitlab.com/ci/yaml/#global-keywords
* https://docs.gitlab.com/ci/yaml/#default
* https://docs.gitlab.com/ci/yaml/#id_tokens
=> fix: gitlab example for trusted publishing

content/packages-and-modules/getting-packages-from-the-registry/resolving-eacces-permissions-errors-when-installing-packages-globally.mdx
Simplify the steps a bit:
- Backing up the computer and creating the directory is not necessary, since it's created automatically  by npm.
- Use the ~/.local directory which is the standard place for user-specific software, and likely to already be in the user's PATH.
- `export` is not needed since PATH is already exported.
- Add a note for zsh which doesn't use ~/.profile.
- Use a different package as an example, since jshint is not regularly updated, and linters should generally be in `devDependencies` and used through npm scripts.
- Ensure the user can run the installed tool.
- Remove mention of `NPM_CONFIG_PREFIX` which is not sufficient, since the PATH still needs to be updated to use global tools.
=> docs: improve documentation on resolving EACCES

src/components/variant-select.js
- Keyboard focus order is not logical for the list items under 'Select CLI Version' button. keyboard focus is moving twice upon the version list items.
https://github.com/user-attachments/assets/e3306e28-11ae-48be-b115-17c4ddabf62e
=> [Fix Accessibility]: Add tabIndex to VariantItem for improved accessibility

src/components/search.js, src/components/table-of-contents.js, src/components/variant-select.js
- Enhanced search result items with descriptive ARIA labels including position and hierarchy information
-  Added ARIA labels to table of contents navigation items and restructured nested navigation with proper SubNav components
This PR improves accessibility for screen readers by adding descriptive ARIA attributes to search results and table of contents navigation, ensuring users can understand item context and position within the navigation structure.
=> [Fix Accessibility]: Enhance accessibility by adding ARIA attributes to table of content
